# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/vlsilab.boeblingen.ibm.com/u/lyhlu/vol2/HEVC/snap/actions/hdl_h265enc/ip/fifo_512_128/fifo_512_128.xci
# IP: The module: 'fifo_512_128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/vlsilab.boeblingen.ibm.com/u/lyhlu/vol2/HEVC/snap/actions/hdl_h265enc/ip/fifo_512_128/fifo_512_128.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512_128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /afs/vlsilab.boeblingen.ibm.com/u/lyhlu/vol2/HEVC/snap/actions/hdl_h265enc/ip/fifo_512_128/fifo_512_128_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /afs/vlsilab.boeblingen.ibm.com/u/lyhlu/vol2/HEVC/snap/actions/hdl_h265enc/ip/fifo_512_128/fifo_512_128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /afs/vlsilab.boeblingen.ibm.com/u/lyhlu/vol2/HEVC/snap/actions/hdl_h265enc/ip/fifo_512_128/fifo_512_128.xci
# IP: The module: 'fifo_512_128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/vlsilab.boeblingen.ibm.com/u/lyhlu/vol2/HEVC/snap/actions/hdl_h265enc/ip/fifo_512_128/fifo_512_128.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /afs/vlsilab.boeblingen.ibm.com/u/lyhlu/vol2/HEVC/snap/actions/hdl_h265enc/ip/fifo_512_128/fifo_512_128_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /afs/vlsilab.boeblingen.ibm.com/u/lyhlu/vol2/HEVC/snap/actions/hdl_h265enc/ip/fifo_512_128/fifo_512_128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
